import { createServer } from 'node:http';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { openDatabase, Store } from '../server/db.js';
import { createApp } from '../server/app.js';
import { Worker } from '../server/worker.js';
import { extractArticle } from '../server/article.js';

const paragraphs = Array.from({ length: 45 }, (_, i) => `<p>On walk ${i + 1}, we followed the river beyond the old bridge. The reeds bent in the wind, and the water carried leaves past our feet. We stopped to notice the small things: a feather, a bright stone, the sound of distant birds. Taking time to look changes how familiar places feel.</p>`).join('');
let short = false;
const fixture = createServer((_req, res) => {
    res.setHeader('Content-Type', 'text/html');
    res.end(short ? '<html><title>A visual site</title><nav>Shop Home About</nav><h1>Hello</h1></html>' : `<!doctype html><html><head><title>A slower way home</title><meta name="author" content="A. Walker"></head><body><nav>Discardnavigation <a href="/shop">Shop</a></nav><article><h1>A slower way home</h1><p>A long walk gives us room to think, and time to return to the everyday with fresh eyes. ${'We watch the river move, and listen to the birds. '.repeat(8)}</p><h2>Along the river</h2>${paragraphs}<blockquote>Keep a little room for curiosity.</blockquote><ul><li>Bring a notebook</li><li>Follow the footpath</li></ul><p><a href="/another-walk">Another walk</a> <a href="javascript:alert(1)">Unsafe link</a></p><pre><code>const walk = '&lt;slow&gt;';</code></pre><p>Finalparagraphuniqueterm ends our journey.</p><img src="/tracking.gif" onerror="window.evil=true"><iframe srcdoc="evil"></iframe></article><footer>Discardfooter</footer></body></html>`);
});
await new Promise<void>(resolve => fixture.listen(0, '127.0.0.1', resolve));
const url = `http://127.0.0.1:${(fixture.address() as { port: number }).port}/article`;
const directory = await mkdtemp(path.join(tmpdir(), 'shelf-reader-'));
const store = new Store(openDatabase(directory));
const { app, notify } = createApp(store, directory, () => true);
const worker = new Worker(store, directory, notify, 1);
const browser = await chromium.launch();
const output = process.env.REVIEW_DIR || 'test-results';
await mkdir(output, { recursive: true });
try {
    const origin = await app.listen({ host: '127.0.0.1', port: 0 });
    const { item } = store.save({ url });
    await worker.start();
    const waitCapture = async () => {
        const until = Date.now() + 90000;
        while (Date.now() < until && store.item(item.id)?.status !== 'done') await new Promise(r => setTimeout(r, 250));
        assert.equal(store.item(item.id)?.status, 'done', store.item(item.id)?.error || 'Capture timed out');
    };
    await waitCapture();
    const captured = store.item(item.id)!;
    assert.ok(captured.article);
    assert.ok(captured.thumb_path);
    assert.ok(captured.article.text.length > 10000);
    assert.ok(captured.article.text.includes('Finalparagraphuniqueterm'));
    assert.ok(!captured.article.text.includes('Discardnavigation'));
    assert.ok(!captured.article.text.includes('Discardfooter'));
    assert.equal(store.list({ q: 'Finalparagraphuniqueterm' }).total, 1);
    const content = JSON.stringify(captured.article.content);
    assert.ok(!/javascript:|onerror|iframe|tracking.gif/.test(content));
    assert.ok(content.includes('/another-walk'));
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(`${origin}/item/${item.id}`);
    await page.locator('.reader-content').waitFor();
    assert.equal(await page.getByRole('button', { name: 'Read', exact: true }).getAttribute('aria-pressed'), 'true');
    assert.ok(await page.locator('.reader-content h2').count());
    assert.ok(await page.locator('.reader-content blockquote').count());
    assert.equal(await page.locator('.reader-content script,.reader-content img,.reader-content iframe').count(), 0);
    assert.equal(await page.locator('.reader-content a').first().getAttribute('href'), new URL('/another-walk', url).href);
    await page.screenshot({ path: path.join(output, 'reader-desktop.png') });
    await page.locator('.reader-panel').evaluate(el => { el.scrollTop = (el.scrollHeight - el.clientHeight) * .45; });
    await page.waitForFunction(async id => { const item = await (await fetch('/api/items/' + id)).json(); return item.reading_progress > .4; }, item.id);
    await page.getByRole('button', { name: 'Full page', exact: true }).click();
    await page.locator('.full-shot').waitFor();
    await page.getByRole('button', { name: 'Read', exact: true }).click();
    assert.ok(await page.locator('.reader-panel').evaluate(el => el.scrollTop > 1000));
    await page.getByRole('button', { name: 'Mark as read', exact: true }).click();
    await page.getByRole('button', { name: 'Mark unread', exact: true }).waitFor();
    await page.reload();
    await page.locator('.reader-content').waitFor();
    assert.ok(await page.locator('.reader-panel').evaluate(el => el.scrollTop > 1000));
    assert.equal(store.item(item.id)?.is_read, true);
    await page.getByRole('button', { name: 'Mark unread', exact: true }).click();
    await page.getByRole('button', { name: 'Mark as read', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Close detail' }).click();
    await page.getByRole('button', { name: 'Switch colour theme' }).click();
    await page.goto(`${origin}/item/${item.id}`);
    await page.locator('.reader-content').waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('.reader-panel').evaluate(el => { el.scrollTop = 0; });
    await page.screenshot({ path: path.join(output, 'reader-mobile-light.png') });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.equal(await page.locator('.reader-panel').evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await page.setViewportSize({ width: 320, height: 700 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    short = true;
    const probe = await browser.newPage();
    await probe.goto(url);
    assert.equal(await extractArticle(probe), null, 'non-article falls back to screenshots');
    await probe.close();
    await fetch(`${origin}/api/items/${item.id}/recapture`, { method: 'POST' });
    await waitCapture();
    assert.deepEqual(store.item(item.id)?.article, captured.article, 'unsuccessful extraction preserves saved article');
    assert.equal(store.list({ q: 'Finalparagraphuniqueterm' }).total, 1);
    const video = store.save({ url: 'https://youtu.be/dQw4w9WgXcQ?t=42' }).item;
    store.update(video.id, { status: 'failed', title: 'A saved YouTube video' });
    let embeds = 0;
    await page.route('https://www.youtube-nocookie.com/**', route => { embeds++; return route.fulfill({ contentType: 'text/html', body: '<p>Player fixture</p>' }); });
    await page.goto(`${origin}/item/${video.id}`);
    await page.getByRole('button', { name: 'Play video', exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: 'Watch', exact: true }).getAttribute('aria-pressed'), 'true');
    assert.equal(embeds, 0, 'player does not load before Play');
    await page.screenshot({ path: path.join(output, 'video-mobile.png') });
    await page.getByRole('button', { name: 'Play video', exact: true }).click();
    await page.locator('.video-frame iframe').waitFor();
    assert.match((await page.locator('.video-frame iframe').getAttribute('src'))!, /youtube-nocookie.com\/embed\/dQw4w9WgXcQ.*start=42/);
    assert.equal(await page.locator('.video-frame iframe').getAttribute('referrerpolicy'), 'strict-origin-when-cross-origin');
    await page.getByRole('button', { name: 'Full page', exact: true }).click();
    assert.equal(await page.locator('.video-frame iframe').count(), 0);
    const icon = await page.locator('link[rel="icon"]').getAttribute('href');
    assert.ok(icon?.startsWith('data:image/svg+xml,'));
    assert.ok(decodeURIComponent(icon!).includes('🔗'));
    assert.equal(await page.evaluate(async href => { const img = new Image(); img.src = href!; try { await img.decode(); return img.naturalWidth > 0; } catch { return false; } }, icon), true);
    assert.deepEqual(errors, []);
    console.log('PASS: full article capture, safe formatting, complete search, screenshot switching, reading state, position restoration, desktop/mobile themes, extraction fallback and recapture preservation.');
} finally {
    await browser.close();
    await worker.stop();
    await app.close();
    store.db.close();
    await new Promise<void>(resolve => fixture.close(() => resolve()));
    await rm(directory, { recursive: true, force: true });
}
